[package]
name = "extentria"
version = "0.0.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
linux-raw-sys = { version = "0.12.0", features = ["ioctl"] }
zerocopy = { version = "0.8.33", features = ["simd", "std"] }
zerocopy-derive = "0.8.33"
