[package]
name = "tumulus"
version = "0.0.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.3", features = ["rayon"] }
clap = { version = "4.5", features = ["derive"] }
extentria.workspace = true
hex = "0.4"
jiff = "0.2"
machine-uid = "0.5"
memmap2 = "0.9"
rayon = "1.10"
rusqlite = { version = "0.35", features = ["bundled", "blob"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lloggs = "1.3"
tracing = "0.1"
uuid = { version = "1.19", features = ["v4"] }
walkdir = "2.5"
